# Generated by Django 4.1.3 on 2023-03-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codeflix', '0004_course_coursemodule_profile_delete_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
